spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kang
    url: jdbc:mysql://localhost:3306/yupi
#设置session失效时间
  session:
    timeout: 86400
server:
  port: 8080
